### ISSUE TITLE
 صفحه چت UI - Header

### ISSUE THREAD

**Issue by Torabi-srh** [AlephbaSystem/MobileHRM#8]
###  صفحه چت #6 

- [x] اندازه 3 ایکون (یوزر - نوتیفیکیشن - افزودن/جدید) درست نمی باشد باید یک اندازه باشند.
- [x] در ایکون یوزر - نوتیفیکیشن سایز دایره / فریم باید با هم یک اندازه شوند و خود آیکون هم باهم برای مثال در فیگما دایره دور ایکون ها 44x44 هست و خود ایکون ها 20x20
- [x] ایکون/عکس یوزر border با رنگ بنفش دارد. (7B61FF#) 
- [x] ایکون بک و ایکون نوتیفیکیشن سایه ندارند.
- [x] مارجین یا فاصله های افقی و عمودی رعایت نشده اند.
- [x] فونت سرچ اشتباه است و باید از فنت `Quicksand` و سایز `Regular` استفاده شود.
- [x] برای سرچ بار سایه اعمال شود.
- [x] رم سیستم چطوره ؟ 
- [x] رنگ ایکون افزودن مشکل دارد.
- [x] رنگ زره بین سرچ تغییر کند.

**Comment by Moein13r** [comment]
سلام  رم سیستم  خیلی خوبه 
دریافت شد.
